### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by HenryHeffan** [moneroexamples/access-blockchain-in-cpp#2]
Hi.
When building using version 0.10.1 of Monero (and adding the libraries from that build into the /opt/bitmonero-dev/headers and library's), the code attempts to link to cryptonote_core/blockchain_storage.h but after examining the Monero project this file does not exist. It is clear the structure of the Monero project has changed, but I am new to Monero and don't know enough about the structure of what the program used to be like, so I don't know how to attempt to fix this problems. Any help would be appreciated.

**Comment by moneroexamples** [comment]
Sorry, closed by accident. I can make it up to day. Since access-blockchain-in-cpp was developed many has changed in monero. Are you interested in this particular project only, or more in general? If the later, than maybe you can have a look at more up to date projects, for example

- https://github.com/moneroexamples/onion-monero-blockchain-explorer

**Comment by moneroexamples** [comment]
Just updated this example to work with current development monero version. Please dont hesitate to ask if you have any question or something does not work as it should.

**Comment by HenryHeffan** [comment]
Hi. I did not realize that rpc calls could be done locally to access the blockchain, so I don't need to use the monero libraries to parse (and then figure out how to format blocks) from the blockhain. I'm sorry for waisting your time updating the project.

**Comment by moneroexamples** [comment]
No problem. I will close the issue. If something else, you can reopen it or make new one.
